# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
      - id: markdownlint
        name: markdownlint-fix
        alias: markdownlint-fix
        args: ["--fix"]
        stages: [manual]

  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
        exclude: "(_typos.toml|.gitignore|.dockerignore)"
