[default.extend-words]
# Don't correct the abbreviation `ba` for revisions.
ba = "ba"

[files]
extend-exclude = [
    # Exlude this file, which contains examples of typos
    "_typos.toml",
    ".gitignore"
]
