name: Automerge Release PRs

on:
  pull_request_target:
    branches: [ main ]

env:
  TEST_TAG: ${{ github.event.repository.full_name }}:test

jobs:

  test_docker_container:
    name: Build and Test Docker image
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Docker image
        run: |
          docker run --rm -i ${{ env.TEST_TAG }} beet version

  automerge_release:
    if: github.event.label.name == 'release'
    needs: test_docker_container
    runs-on: ubuntu-latest

    steps:
      - name: Enable Automerge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve
        uses: hmarr/auto-approve-action@v3.2.1

      - uses: actions/checkout@v3
      - run: rm -rf .git/hooks

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install js-yaml

      - name: "Release"
        id: create-release
        uses: "actions/github-script@v6.4.1"
        with:
          script: |
            const script = require('./.github/workflows/github-release/github-create-release.js')
            return await script({github, context, core})
