# https://docs.github.com/en/actions

name: "Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Get repo variables
        id: get_repo_vars
        uses: mikefarah/yq@master
        with:
          cmd: yq -o "json" '.' ./repo-vars.yaml

      - name: "Add repo variables to ENV"
        run: |
          echo "PROJECT_VERSION=${{ fromJSON(steps.get_repo_vars.outputs.result).project_version }}" >> $GITHUB_ENV
          echo "LSIO_VERSION=${{ fromJSON(steps.get_repo_vars.outputs.result).lsio_version }}" >> $GITHUB_ENV
          echo "BA_VERSION=${{ fromJSON(steps.get_repo_vars.outputs.result).ba_version }}" >> $GITHUB_ENV

      - name: "Prep for Release"
        uses: "actions/github-script@v6.3.3"
        with:
          script: |
            const script = require('./.github/workflows/github-release/github-release.js')
            await script({github, context, core})

      - name: "results"
        if: ${{ env.RELEASE_NEEDED }}
        run: |
          echo ${{env.PROJECT_VERSION}}
